name: lcr-dataengineering-sql
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - sqlalchemy>=2.0
  - python-dotenv
  - pyodbc            # SQL Server
  - psycopg2          # Postgres (ou psycopg2-binary via pip)
  - pymysql           # MySQL (puro python, bom no Windows)
  - pyarrow           # parquet, se usar
  - pip
  - pip:
      - -e .
